### ISSUE TITLE
TERRAFORM 0.0.0.3 - Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

### ISSUE THREAD

**Issue by nirupamjm** [EtricKombat/terraform#1]
# firstec2.tf

![image](https://user-images.githubusercontent.com/68326831/104678927-a0122800-5740-11eb-9f5e-2346c5a757ac.png)

**Comment by nirupamjm** [comment]
After using terraform apply command, It is not generating EC2.

**Comment by nirupamjm** [comment]
![image](https://user-images.githubusercontent.com/68326831/104680273-963df400-5743-11eb-90ce-96305b7be6b4.png)

**Comment by nirupamjm** [comment]
![image](https://user-images.githubusercontent.com/68326831/104680326-ba013a00-5743-11eb-92e4-17c0058f134c.png)

**Comment by EtricKombat** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/SLB_c_ayRMo/0.jpg)](https://www.youtube.com/watch?v=SLB_c_ayRMo)

**Comment by nirupamjm** [comment]
issue fixed by simply saving the file before using terraform commands.
